### ISSUE TITLE
Deep Zoom Sync

### ISSUE THREAD

**Issue by sanfordd** [sciencehistory/chf-sufia#1003]
Dig into memory limits on syncing the deep zoom bucket between staging and production.

**Comment by sanfordd** [comment]
Seems to be more stable without the unmatched deleting of dzi tiles. It's taking a while to run but fedora-stage shows a flat RAM usage.

**Comment by sanfordd** [comment]
It seems to have run successfully, but doing so still caused some problems for the box running it. It might be worth batching up.

**Comment by sanfordd** [comment]
The aws cli list is generating unreasonably long sets of lists even on a small page set. Looping over that doesn't seem to be very useful.

**Comment by jrochkind** [comment]
not sure what you mean, but let me know if you want me to take a look!

**Comment by sanfordd** [comment]
Solved by throwing it on a larger box and dropping concurrency.
