### ISSUE TITLE
SSL Cert 

### ISSUE THREAD

**Issue by sanfordd** [sciencehistory/chf-sufia#1005]
Add SSL cert management features to ansible scripts.

**Comment by sanfordd** [comment]
The old Let's Encrypt certs for staging has expired and I don't know if we want to keep managing a LE certificate for an old name on a non-public server. @jrochkind @MDiMeo Any thoughts on just abandoning the old name on staging? I can either roll the LE process into an ansible command or just let the old name fade on staging. Since prod uses a different certificate for pre-launch URLS than staging this won't have any effect on the production site.

**Comment by MDiMeo** [comment]
I'm okay with abandoning the old name.

**Comment by jrochkind** [comment]
I have no opinion, that's fine. By old name you mean "chemheritage"?  I don't care if it remains on staging, unless we want it there so we can make sure it's equivalent to production for testing things.

**Comment by sanfordd** [comment]
I do mean chemheritage. The LE setup is a variation from production either way, so unless we want to add the old name to the main cert like production does (with the corresponding cost which we'd need to check) both options have some divergence. I'll get that adjusted then and see about adding a switch for the future to make it easier when/if we switch out the old name in production.

**Comment by sanfordd** [comment]
Once the deploy is tested and works, I'll let Chuck know we can drop the old name for staging on the DNS records. I'll post something to Slack as a reminder when it happens. I don't think anyone outside of our team is testing anything on staging to need an alert.

**Comment by sanfordd** [comment]
Builds working, now applied to staging. If nothing goes wrong I'll merge and close.

**Comment by sanfordd** [comment]
Done successfully in staging, deployed to production. I'll notify Chuck to remove the old URL with everything working now.
