### ISSUE TITLE
Stop building ruby from source

### ISSUE THREAD

**Issue by sanfordd** [sciencehistory/chf-sufia#1018]
Look into either using renv/RVM, or start maintaining a locally packaged version of our preferred Ruby version. Building from source is one of the more time consuming parts of spinning up a new samvera server.

**Comment by sanfordd** [comment]
@jrochkind mentionng you here to see about any thoughts on renv/RVM rather than system ruby. Building a package is a bit more work on the ops side, but won't involve needing to worry about any compatibility issues. This isn't a very urgent issue.

**Comment by jrochkind** [comment]
not sure. people often say not to use rvm/rbenv in production; people also often do it anyway. 

I use `chruby` on my dev workstation (alternative to rvm/rbenv). I don't know if I'd like it in production. 

Some of the ruby version managers also build from source.  I wonder whether building from source or not is orthogonal to whether to use a ruby version manager. Is there a way to install ruby from binary rather than source that has nothing to do with whether to use rbenv/rvm?  If the goal is installing a compiled binary instead of from source, we can research how to do that on the architecture/OS we've got, which may or may not involve a ruby version manager.

**Comment by sanfordd** [comment]
I think the way to install it other than using renv/RVM would be to put together a package script and make our own .deb file based on a version of ruby and use that. It would require some work to build and test the packaging script, but once that's done it should be quicker to install. Since it's just internal it _hopefully_ won't be too much trouble to pin to our environment.

**Comment by jrochkind** [comment]
There are also ruby installation tools that are separate from version management. I don't know which ones will install from compiled binaries -- and it may depend on the platform you are installing on. 

https://github.com/postmodern/ruby-install
https://github.com/rbenv/ruby-build

I think ruby-build is what rbenv uses under the hood, so rbenv is gonna install from compiled binary if and only if ruby-build does.  Don't know about rvm.

**Comment by sanfordd** [comment]
Rather than using the systems compiled binaries, I mean managing our own compiled binaries made from whatever source version we want to stick with. Relying on the default ones in the OS repository probably won't keep us up to date that well.

**Comment by jrochkind** [comment]
Here's an open ticket on ruby-build which suggests that it is not yet capable of installing a compiled binary, and that it installs from source also. Which would suggest rbenv probably does that, since rbenv uses ruby-build. 

https://github.com/rbenv/ruby-build/issues/42

**Comment by jrochkind** [comment]
looks like `rvm` may be the only option that supports precompiled binaries (at least sometimes). 

rvm is really heavyweight and cludgey and not a great option for production. Just managing our own compiled binaries is probably the better option, alas.

**Comment by sanfordd** [comment]
Skipping rvm seems wise.
Just tossing the link you shared in Slack here (https://launchpad.net/~brightbox/+archive/ubuntu/ruby-ng) so I don't lose track of it.

**Comment by sanfordd** [comment]
Looks like the ruby-ng doesn't allow specific sub-versions of Ruby to be installed which is pretty nuts. That makes it non-viable for our needs.

**Comment by sanfordd** [comment]
So another new, and perhaps final option, is to simply build a base AMI with a few common long build packages (ruby, java) and just deploy that.

**Comment by sanfordd** [comment]
We'll make a playbook to build an server and install the preferred Ruby version from source, then build an AMI and terminate the server. Future builds can use the newly built AMI by changing that value in our ansible settings.
