### ISSUE TITLE
Error Accessing work

### ISSUE THREAD

**Issue by sanfordd** [sciencehistory/chf-sufia#1020]
The work `sn009z42z` cannot be accessed on staging or production. It generates a 401 unauthorized error for admin users.

This may be related to error 37113780 in Honeybadger. Which shot out a `ActiveFedora::ActiveFedoraError: Model mismatch. Expected GenericWork. Got: FileSet` basic note, see Honeybadger for the full trace.

Accessing the work on production rather than staging did not give another Honeybadger error.

https://app.honeybadger.io/projects/53196/faults/37113780

http://staging.digital.sciencehistory.org/works/sn009z42z
http://digital.sciencehistory.org/works/sn009z42z

**Comment by jrochkind** [comment]
something in sufia is eating the error before it even makes it to logs, so sad.

**Comment by sanfordd** [comment]
Well that's going to make actually tracking it down a pain.

**Comment by jrochkind** [comment]
Hmm, `sn009z42z1 is _not_ a work, it's a FileSet.  If it's always been a fileset, then those URLs would never have been expected to work with it. (Sufia's annoying way of reporting that error is a problem). 

But so where did the incoming URL come from triggering the error?

Honeybadger claims the referrer is `https://staging.digital.sciencehistory.org/works/sn009z42z` -- but that URL is an error too, how could it be a referer?  

Could be some kind of weird bot. Honeybadger claims the user-agent was chrome, but bots lie. 

But I don't actually suspect that, really, doesn't seem like the kind of thing a random bot would do (especially with just one url). 

Except if I'm reading it right, the IP address on the first occurence of the error is... _mine_! 

Oh, and yeah, the user-agent matches mine exactly, down to the little fingerprinting details. 

So, okay, it was just something odd going on in my computer, heh.
