### ISSUE TITLE
Ingest workflow pain point: Uploads in user interface prevents other work from being done in browser

### ISSUE THREAD

**Issue by catlu** [sciencehistory/chf-sufia#1021]

**Comment by jrochkind** [comment]
Also the fact that uploads can take many hours is not great, even if it didn't interfere with other work. Maybe we can solve both.

**Comment by sanfordd** [comment]
Another quick note, we ended up with Cloudberry to handle sharing access between the local M drive and S3. The final choice was an upload folder that moves files over, so they are local (for editing and QA purposes) and then moved to the upload folder where a powershell script will shift the files over to S3.

We had to raise the Cloudberry cache size, the current aimed limit will be 1 GB files. Larger individual files will require a change. The thumbs.db and .ds_store files will be deleted and not copied over in the case where they are in folders that are uploaded.

**Comment by jrochkind** [comment]
Closed by #1076
