### ISSUE TITLE
Papers of Herbert H. Dow thumbnail

### ISSUE THREAD

**Issue by catlu** [sciencehistory/chf-sufia#1062]
File is p2676w391_full.tif.

**Comment by jrochkind** [comment]
Some docs on adding collection thumbs is here: https://github.com/sciencehistory/chf-sufia/blob/master/docs/image_crops.md

@HKativa specs for images for collection thumbs are 700x700px square. (This is actually double resolution we display at, for high-res screens).  We usually/preferably name the files `{collection_id}_2x.jpg` Cat puts them somewhere on P drive. Doc above suggests `Othmer Library/Digital Collections/Crops for Hydra Redesign/uncropped_originals/`, but I don't think that exactly matches @catlu's current practice, but somewhere around there. 

@eddierubeiz Start with that doc on how you add it to app? Involves commiting the image to repo, and then running a rake task on production server to associate the image with the collection in db (or fedora, I forget; persisted somewhere).   Let me know if you run into any roadblocks or missing things from docs.

**Comment by jrochkind** [comment]
PS: This is a very hacky procedure, for adding collection thumbs. We did it quick and dirty when we were in the midst of meeting our roll-out deadlines. 

We could prioritize some work to make this smoother, and allow self-service by non-developer staff.

**Comment by eddierubeiz** [comment]
@HKativa and @jrochkind  -- I found the file Cat wanted to use:
P/Othmer Library/Digital Collections - External Access/Crops for Hydra Redesign/cropped_tiffs/collections/p2676w391_full.tif

**Comment by eddierubeiz** [comment]
Which means that I can really take it from there. The instructions are crystal clear. I'll bother you guys if I get stuck.

**Comment by jrochkind** [comment]
Oh and actually reviewing those docs, @HKativa you don't need to make the crop 700x700, just make it square, we can take care of sizing it to the needed size if it's the right aspect ratio (in this case, square).

**Comment by eddierubeiz** [comment]
You don't have to do anything! Cat already made it square.

**Comment by eddierubeiz** [comment]
OK you're all set: https://digital.sciencehistory.org/collections/p2676w391

**Comment by eddierubeiz** [comment]
I'm closing this; let me know if anything needs adjusting.

**Comment by HKativa** [comment]
Looks great - thanks @eddierubeiz!
