### ISSUE TITLE
Fix Solr Role

### ISSUE THREAD

**Issue by sanfordd** [sciencehistory/chf-sufia#1064]
Solr role uses service restarts and not reloads, and needs to be better about tracking actual changes in the file so we aren't restarting or reloading without a reason. Should solve the occasional RSolr errors during ansible updates.

**Comment by sanfordd** [comment]
Fixed, moved the check for solr being installed earlier in the role. This makes it simpler to skip any download/install tasks. Also the restart has been switched to a handler to only run when the solr configuration or schema files change.

**Comment by jrochkind** [comment]
Note you _can_ just tell solr to reload config instead of restart, to get new config and schema, to avoid any solr downtime. This may be worth doing as an enhancement at some point. 

https://wiki.apache.org/solr/CoreAdmin#RELOAD

**Comment by sanfordd** [comment]
@jrochkind So we'll want to do a reload for schema changes, and a restart for memory limit adjustments or other ones which require a full restart.

**Comment by jrochkind** [comment]
Ah, right, memory limit will of course requires a restart, good point. Yeah. That makes it harder I guess.

**Comment by jrochkind** [comment]
Is memory limit in one of those files, solrconfig.xml and schema.xml?  I think it may be elsewhere?  It may be that anything in solrconfig or schema is good with a reload?

**Comment by jrochkind** [comment]
Sweet, that makes it simpler for ansible hopefully. no need to parse files or anything, changes in solr.in.sh require a full restart, changes in solrconfig or schema just a reload.

**Comment by sanfordd** [comment]
Looks like that won't be an issue, most config/schema changes happen in capistrano. The ansible changes for those files only apply when there's a brand new file or file location, which does seem to require a restart. That shouldn't happen unless we're building new boxes or purposely breaking files.
