### ISSUE TITLE
GPDR design changes

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/chf-sufia#1065]
1) **Change the footer** by adding a link to the privacy policy.
- The design should match the bottom line at sciencehistory.org:
- © (year) Science History Institute | Privacy Policy, with the link going to https://www.sciencehistory.org/privacy-policy
2) **Add a banner** at the bottom of the page.
- Again, match the design of the sciencehistory.org .
- Clicking "I accept" should make the banner go away, and save a cookie.
- Note that the main site appears to load a script from an external site (https://cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js ). We probably won't want to do this, but there are lots of open-source projects that offer similar functionality. see e.g. https://github.com/insites/cookieconsent .

**Comment by jrochkind** [comment]
I don't know if there are any concerns about putting the _copyright_ statement specifically on our web site, I think maybe there had previously been concerns about accidentally implying that we held copyright on our assets (which we generally don't), and that might be why we don't have the copyright symbol already.  But I may have gotten the wrong impression, I wasn't involved in any decision that may have happened to leave out the copyright statement thus far, that was Michelle. 

@catlu @mhpmiller @RonBrashear

**Comment by mhpmiller** [comment]
And if there was a more explicit concern about copyfraud, we could always promote Rights and Rights Holder metadata to be displayed alongside Creator and Subject on Collection pages, in searches, etc.

**Comment by eddierubeiz** [comment]
This is working in production. Closing this issue.
