### ISSUE TITLE
Photos from Perkin-Elmer-Applera thumbnail

### ISSUE THREAD

**Issue by HKativa** [sciencehistory/chf-sufia#1070]
File forthcoming; need to go over workflow with Cat.

**Comment by HKativa** [comment]
@eddierubeiz file is 2j62s582j_full.tif. Saved to P:\Othmer Library\Digital Collections - External Access\Crops for Hydra Redesign\cropped_tiffs\collections. If the cropping doesn't work, let me know!

**Comment by eddierubeiz** [comment]
All set: https://digital.sciencehistory.org/collections/2j62s582j
