### ISSUE TITLE
Rohm & Haas Company Archives thumbail

### ISSUE THREAD

**Issue by HKativa** [sciencehistory/chf-sufia#1071]
File forthcoming; need to go over workflow with Cat.

**Comment by HKativa** [comment]
@eddierubeiz file is cz30pt55m_full.tif. Saved to same folder as the others. If crop doesn't work, let me know!

**Comment by eddierubeiz** [comment]
Noted. Should get to it this morning; stay tuned!

**Comment by eddierubeiz** [comment]
Done:  https://digital.sciencehistory.org/collections/cz30pt55m
