### ISSUE TITLE
Document Offboarding procedures and script them

### ISSUE THREAD

**Issue by sanfordd** [sciencehistory/chf-sufia#1072]
Document all employee offboarding procedures carefully to avoid concerns with missing steps and script as much of it as possible to make it simpler to run.

**Comment by HKativa** [comment]
Issues on our radar so far:
Scrambling password for Digital Collections site; revoking access to GitHub, AWS
Expand scope of document to include on-boarding procedures/checklist
Chains of command; access to Confidential folders on P Drive

**Comment by jrochkind** [comment]
Also including _doing_ it for our soon to depart or recently departed employees. :)

**Comment by HKativa** [comment]
Also, exploring the Wiki, I noticed that Anna, Cat, and Michelle are all administrators - need to look into whether or not this should be changed as well.

**Comment by HKativa** [comment]
@sanfordd issue that came up when I debriefing with Cat: there are other old user accounts whose passwords may need to be scrambled:
tuchacz@sciencehistory.org
jklein@sciencehistory.org
aheadley@sciencehistory.org
ncook@sciencehistory.org

**Comment by sanfordd** [comment]
I believe we did  aheadley@sciencehistory.org already, I do not know if we've done the others.

**Comment by jrochkind** [comment]
We could provide a feature to ban certain accounts from login, if it's getting confusing to keep track of "scrambled" passwords. Would not be too hard.

**Comment by sanfordd** [comment]
I'm all in favor of a "lock account" option.

**Comment by HKativa** [comment]
Me too - "lock account" sounds like a good option.

**Comment by sanfordd** [comment]
Added lock out instructions to the wiki based on @eddierubeiz's lockout code. From #1107

**Comment by HKativa** [comment]
Onboarding/offboarding procedures updated and complete as of 7/23/2018: https://chemheritage.atlassian.net/wiki/spaces/HDCSD/pages/446070785/Onboarding+and+Offboarding+Procedures.
