### ISSUE TITLE
Compilation of issues from reviewing PA Digital harvest

### ISSUE THREAD

**Issue by catlu** [sciencehistory/chf-sufia#1074]
Hi, Cat and Jonathan.

We have the collection harvesting now in our test aggregator. You can see the records here (refresh to see the number climb!):

http://test.padigital.org/?f%5Bcontributing_institution_sim%5D%5B%5D=Science+History+Institute&per_page=100

We're not sure why a placeholder thumbnail is displaying in our frontend. We've seen that recently with a few other collections. The URLs work and that's what matters. People that find your items in the DPLA portal will be taken to your system, not ours, so it won't affect things.

Let me know what you think. If everything looks good, we'll add these to our production aggregator, which is where we stage finalized stuff for our DPLA harvest.

Thanks!

-------------

@jrochkind mentioned in email:

> One issue I first noticed in just spot-checking some of them. 
>  
> This record: http://test.padigital.org/catalog/dplapa:SHINST_0c483k298
>  
> Has a title in your system of “Emblema VII. Fit pullus”
>  
> The actual title in our system, and I believe our OAI-PMH feed, is: “Emblema VII. Fit pullus à nido volans, qui iterùm cadit in nidum.”
>  
> It’s getting cut off before the “à”?  Does your system have trouble with non-ascii Unicode?  That would be unfortunate. 
>  
> https://digital.sciencehistory.org/works/0c483k298
>  
> https://digital.sciencehistory.org/oai?verb=GetRecord&metadataPrefix=oai_dc&identifier=oai:sciencehistoryorg:0c483k298
>  
> There are records in DPLA itself including Unicode, specifically including this record, eg:
>  
> https://dp.la/item/1d8fda24a861f0384168e3ddf4256392
>  
> Note that title starts with “À”

**Comment by catlu** [comment]
'Types' seem to be showing up inconsistently--

here's one where it came through: http://test.padigital.org/catalog/dplapa:SHINST_00000002j

and here's one without even though it's in our records: http://test.padigital.org/catalog/dplapa:SHINST_ww72bc38m

**Comment by catlu** [comment]
Hillary Kativa [4:08 PM]
okay, then there are definitely a bunch of records i've seen where not all the subjects come through

**Comment by HKativa** [comment]
Found another issue with processing special characters:
http://test.padigital.org/catalog/dplapa:SHINST_fb4948403

Note, "Publisher" renders as "Schwa?nder, Johann Georg" rather than "Schwänder, Johann Georg"

Original Samvera record: https://digital.sciencehistory.org/works/fb4948403
