### ISSUE TITLE
Upload failing for wm117p65j

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/chf-sufia#1079]
Go to: 
https://digital.sciencehistory.org/concern/generic_works/wm117p65j/edit#files
Drag 8 tiffs into the "Drop Files Here" box; cancel option flips to delete
Click "Save" which takes you back to https://digital.sciencehistory.org/works/wm117p65j .
None of the thumbnails appear; in fact there's only the one placeholder x image, instead of one for each of the eight files.

**Comment by jrochkind** [comment]
weird that we got no errors. But, as I know cause I've been fighting with it, the code around this is a mess. (I have not committed any changes to master yet, so this is not cause of a recent code change). 

Wait, the files aren't showing up at all, they are not showing up without derivatives. So, not sure what to do about this except upload the files again. 

Except uploading the files again does not work? Oh, what a mess.

**Comment by jrochkind** [comment]
Wait, we have no workers. That would explain it. @sanfordd no workers seem to be running in prod, on either server.

**Comment by eddierubeiz** [comment]
The resque workers had disappeared, ultimately due to an outage last Thursday.
Dan restarted resque, which brought back the workers at https://digital.sciencehistory.org/admin/queues/working .
