### ISSUE TITLE
BrowseEverything integration test ( #1021 )

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/chf-sufia#1093]
#1021, needs a painful integration test

**Comment by jrochkind** [comment]
https://github.com/aws/aws-sdk-ruby/issues/724

**Comment by jrochkind** [comment]
If you _really_ wanted a project, you could take the source code for https://github.com/jkrall/mock-aws-s3 and fix it to work with current AWS ruby SDK. :)

**Comment by eddierubeiz** [comment]
No big deal!

**Comment by eddierubeiz** [comment]
This looks extremely helpful. I'm already using stub_responses but this is the first time I've seen put_object and get_object. I've gotten pretty far by requesting the fake URI for my fake s3 files from the stubbed s3 client, and *then* using stub_request to point that fake URI at a local tiff file. But this looks less hacky. Thanks for the tip @jrochkind!
