### ISSUE TITLE
Add title and link to Beckman hero image on homepage

### ISSUE THREAD

**Issue by HKativa** [sciencehistory/chf-sufia#1100]
Update photo of Arnold Beckman used on Featured Collection banner on homepage to mimic features of hero image (Wilson College Chemistry Club) at top of homepage:

Add title "Portrait of Arnold O. Beckman"  
Add link to this record: https://digital.sciencehistory.org/works/wm117p231

**Comment by eddierubeiz** [comment]
Per our discussion, I'll fold this in to the "recent items" ticket, since we're modifying that part of the site anyway.

**Comment by HKativa** [comment]
Thanks @eddierubeiz!

**Comment by eddierubeiz** [comment]
I have a basic version of this working in dev, btw.

**Comment by eddierubeiz** [comment]
Done!
