### ISSUE TITLE
implement lock out feature for accounts

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/chf-sufia#1107]
to be used for staff that's left.

**Comment by jrochkind** [comment]
@HKativa i think we recentlyhad a list of all accounts of past staff members to double check? Can you include it here again? Thanks!

**Comment by jrochkind** [comment]
@eddierubeiz I'd anticipate adding a new column to the user's table -- maybe `locked_out` default false? Alternative `active` default true, heh. 

Then we use [this](https://stackoverflow.com/questions/15864554/check-if-user-is-active-before-allowing-user-to-sign-in-with-devise-rails) devise feature to get devise to not let people log in if they are not active (or are locked_out). 

Note I've already overridden the `active_for_authentication?` method to implement the "temporarily lock everyone out from logging in" feature, so it would involve adding more logic to that existing custom method. 

As always, just ask if you want advice or anything else!

**Comment by HKativa** [comment]
@jrochkind here's the list of past staff member accounts that need to be double-checked:

tuchacz@sciencehistory.org
jklein@sciencehistory.org
aheadley@sciencehistory.org
ncook@sciencehistory.org

@sanfordd thought Anna's had been scrambled already, but no word on the others.

**Comment by jrochkind** [comment]
thanks @HKativa . Once we implement this feature, it won't matter if they have been scrambled already, we'll just mark them all inactive/locked out with the new feature.

**Comment by HKativa** [comment]
@jrochkind good point. For the sake of thoroughness, I've updated the list above to include all past staff members whose accounts should be locked out, regardless of whether or not the passwords have been scrambled.

**Comment by jrochkind** [comment]
Deployed lock out feature, marked the 7 users in above list as locked out, eg

```
hydep@jobs1-prod:/opt/sufia-project/current$ RAILS_ENV=production bundle exec rake chf:lock_out[tuchacz@sciencehistory.org]
Done. User 'tuchacz@sciencehistory.org' can no longer log in to the site.
```

**Comment by eddierubeiz** [comment]
Thanks @jrochkind!
