### ISSUE TITLE
Update Bundler

### ISSUE THREAD

**Issue by sanfordd** [sciencehistory/chf-sufia#1109]

**Comment by sanfordd** [comment]
Bundler requires a y/n response when installing versions that conflict with the current one, mainly seen in downgrades. This is an issue with ansible eee https://github.com/ansible/ansible/issues/30217

We can either just have it keep up to date with the current bundler, pin to a version but not be able to easily roll back, or look into just passing along shell commands.
@jrochkind Do you have a preference? I'm leading to the second for now.

**Comment by jrochkind** [comment]
I think it would be worth filing a GH Issue with bundler asking for a way to do that without an interactive y/n prompt. 

In the meantime, I agree with the second one, if that means "pin to a version but not be able to easily roll back".   Auto-upgrading whenever a new bundler version comes out is dangerous, cause sometimes the new versions do have bugs. (Although they would mostly only exhibit on "cap deploy", it still seems like asking for trouble).  And trying to automate interaction with a "y/n" prompt also seems like asking for trouble, I agree.

**Comment by sanfordd** [comment]
There are ways to bypass the y/n, but sadly the ansible gem module doesn't have a way I really like to do it. We might be able to overwrite the executable, but that seems like bad practice. We could use the the yes command, but avoiding shell commands helps keep things simpler.

**Comment by jrochkind** [comment]
If there's an option to bundler to skip the y/n, but the ansible module doesn't support it, I suppose one option would be contributing an enhancement back to the ansible module. 

but I'm totally okay with "pin to a version but not be able to easily roll back" too, if you think that's the reasonable choice at present. If it becomes a problem for some reason, we can always deal with it then.

**Comment by sanfordd** [comment]
The usual trick is something like `yes | gem install bundler -v X.Y.Z` but we'd need to make it a shell command ansible's pushing out which removes some of the safety of using the modules rather than just bash scripts.

**Comment by jrochkind** [comment]
Oh yeah, I'm not a fan of the `yes` trick. Bundler changes it's UI so some _other_ prompt comes first, you've just entered 'y' to something else. 

I think it might ideally be worth filing an issue with bundler asking for a command line or ENV option to be non-interactive in this case. Ideally. Maybe not actually. :)

**Comment by jrochkind** [comment]
I'm unable to duplicate the particular "y/n" prompt you describe, doing `gem install bundler -v x.y.z` on my dev box, where x.y.z is less than current version. Weird.

**Comment by sanfordd** [comment]
I'll do some tests to see what might be going on with that.

**Comment by sanfordd** [comment]
A quick summary of what we've discovered.
The `gem update  --system` when updating rubygems also grabs a current bundler.
This becomes a default gem which ruby will warn about before replacing. If you install bundler normally and don't update rubygems you can easily swap versions.
We can override this with the `--force` option on a gem, but that introduces the potential to install bundler versions that do not work with our version of ruby. Which is bad.

We're going to, for the moment, not have the ability to use arbitrary bundler versions until this can be done in a better manner.

**Comment by sanfordd** [comment]
We're pinning rubygems to a certain version and we'll just keep the version of bundler it uses. We can move up and down rubygems versions as needed.
