### ISSUE TITLE
Unable to batch ingest using local files option

### ISSUE THREAD

**Issue by HKativa** [sciencehistory/chf-sufia#1114]
Scenario: You are an admin. Under "Works," you select "Batch Create." Under "Add Local Files," you click "Add Folder" and select a folder on the M drive. Under "Descriptions," you enter metadata for "Identifier," "Creator," "Date of Work," "Genre String," "Extent," "Subject," "Rights," and "File creator." You set "Visibility" to "Your Institution." Under "Share," you share editing privileges with another user. After clicking save, you are redirected to the homepage for your works, advised that files are processing in background and you may need to refresh page to see them. However, files never show up. No user notifications that files were imported.

Bug manifested after merging new ingest function for S3. Ingests following this process failed in both production and staging.

**Comment by jrochkind** [comment]
https://app.honeybadger.io/projects/53196/faults/38309590

**Comment by jrochkind** [comment]
@HKativa I'm guessing you may have selected "Format" choices for the images too, on the "files" tab maybe?  You didn't include this in your script, but based on the nature of the error, I think it might have happened (and might be relevant to the bug)?  Can you confirm or deny? :)

**Comment by HKativa** [comment]
@jrochkind Good catch! Yes, I would have selected a "Format" choice, I think "Mixed Material" in this particular instance.
