### ISSUE TITLE
New drop-down value for Creator field 

### ISSUE THREAD

**Issue by HKativa** [sciencehistory/chf-sufia#1122]
Add "Manner of" to the drop-down for "Creator" field, after "Interviewer" and before "Manufacturer"

**Comment by eddierubeiz** [comment]
Oh, looks like we'll need an RDF predicate to associate with this property.
We can mint a local one or use an existing vocab. See https://github.com/sciencehistory/chf-sufia/blob/master/spec/models/generic_work_spec.rb for examples.

**Comment by jrochkind** [comment]
In my memory Cat, as metadata manager, would formerly suggest RDF predicates at the point she asked for new properties/values requiring them.

**Comment by eddierubeiz** [comment]
Per discussion with Hillary - this is actually a Past Perfect metadata term, and it refers to the relationship "in the manner of", as in "in the manner of Michelangelo".
Getty does refer to it as "manner of"; subject ID 300404288 .

**Comment by jrochkind** [comment]
Maybe there's already a standard RDF predicate URI people use for the Getty term? Or else we could just make up a local one. With Cat's absence, I'm not sure who makes metadata control decisions like this?

As we're adding it in the "creator" group, we may have to look at our existing code around that, particularly citation display and export stuff, to make sure it's handled as desired. Like we probably _don't_ want the "in manner of" person included as an author/creator in citation display/export.... I think.

**Comment by eddierubeiz** [comment]
Cat confirmed http://vocab.getty.edu/page/aat/300404288  works great. Will need to add Getty to the namespaces for OAI or that will break...

**Comment by eddierubeiz** [comment]
BTW Cat was providentially swinging by the office today so I didn't even have to email her. @catlu ex machina!

**Comment by jrochkind** [comment]
wow, good call on catching the need for OAI namespaces!  I wonder if we can add something to our testing infrastructure to make sure if we accidentally added something that wasn't properly declared in our OAI namespaces, the test would fail. (Or maybe the current tests will already do that, but I think they may not).  Cause I don't want to count on us remembering all the places that might have be tweaked every time we tweak the RDF URIs.

**Comment by eddierubeiz** [comment]
Maybe just generate the XML for a record and run it through the parser? If the namespaces aren't there it won't validate and the test will fail. If we screw up the XML in some other way it will also fail.

**Comment by jrochkind** [comment]
I'm not totally sure that's true depending on what you mean by "the parser", that it will insist any namespaces are declared. 

I also realize that new fields we add _might_ not show up in OAI-PMH export at all unless we take positive action to make it so -- and we might not care if they don't, as PA Digital/DPLA may not make any use of a "manner of" field so there may be no reason to vend it to them.

**Comment by eddierubeiz** [comment]
Oh sorry. I should have said "a strict XML parser" rather than "a parser". https://github.com/sciencehistory/chf-sufia/blob/master/app/models/chf/oai_dc_serialization.rb also supports your contention that we may not even need to worry too much about it. Come to think of it, "In the manner of" is kind of a terrible fit when it comes to the definition of a DC "creator", so we may not want to put it in there, as you say. (If I draw a picture "in the manner of" Picasso and then try to sell it to you for a hundred million on the strength of its having DC:creator Picasso, you might not agree to buy it from me.)

**Comment by jrochkind** [comment]
@HKativa We already have a 'creator' type called "after" -- can you explain how this one differs?

If we do want them both -- should the 'manner of' values show up in the 'creator' facet?

**Comment by eddierubeiz** [comment]
Did a couple minutes' research. Interestingly, if we use the Getty definitions, the distinction appears to be:
* "After" implies that an unknown artist made a **deliberate** attempt to copy a known artist, whereas
* "Manner of" means the cataloged work "does not seem to be a deliberate copy" of the known artist.
Whether or not we care about these shades of meaning, I'm still going to forge ahead and see if I can get this working, as I want to get a better sense of all this from a tech perspective. Worst case,  we don't merge the PR. :)

Getty's URIs are:

**After:**
* http://vocab.getty.edu/aat/300404286
* http://www.getty.edu/vow/AATFullDisplay?find=&logic=AND&note=&subjectid=300404286

**Manner of:**
* http://vocab.getty.edu/aat/300404288
* http://www.getty.edu/vow/AATFullDisplay?find=&logic=AND&note=&subjectid=300404288

**Comment by jrochkind** [comment]
"After" values are currently included in our facet labelled "Creators" (which is called "maker_facet" internally for legacy reasons). 

https://github.com/sciencehistory/chf-sufia/blob/master/app/indexers/chf/generic_work_indexer.rb#L21-L23

There is some place in our code where we list all the "maker/creator" facets in an array for configuration, that this part of code isn't actually using, not sure if it should be, or if maybe it really is particular to the indexer what fields we want to index in facet. 

So if "after" is in there, and we add "manner of", it probably should be too. Or we could decide to remove them both. 

Anyway, that's the code where you'd have to add the new "manner of" to get it in "Creators" facet.

**Comment by HKativa** [comment]
@jrochkind I confirmed the differentiation between "after" and "manner of" with Stephanie (Museum Collections Manager) before creating the ticket and the distinction is as @eddierubeiz summarized. In addition, "after" is also applied to works that are copies of a work in another form (such as a painting that mimics a scene first depicted as an engraving).

**Comment by eddierubeiz** [comment]
This appears to be working in Staging, btw: https://staging.digital.sciencehistory.org/works/6w924c92w
