### ISSUE TITLE
Date range dropdown: check that start date is before end date before running search.

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/chf-sufia#1125]
Not sure what's up with this one, but it's got a referrer of an item page, so it may be a URL generated by our app itself causing an error, which is more troublesome than some human or bot constructed external URL causing an error. 

## Backtrace

    line 222 of [PROJECT_ROOT]/app/controllers/catalog_controller.rb: index

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53196/faults/38442607)

**Comment by eddierubeiz** [comment]
Just noting that the date range is 1942 - 1045.

**Comment by eddierubeiz** [comment]
It's easy to reproduce this:

- Start on any page of the site that has the Search box in the top right. An item record works fine. In the case above, the user started at https://digital.sciencehistory.org/works/ns064656v 
- Click on the "Search" box.
- Enter an arbitrary search phrase, (In the case above, the person entered  _Company b_ .)
- In the grey "Limit Dates" dropdown, enter an end date before the start date. In the case above, the user clearly intended 1942 - 1945, but they were using a cellphone and entered 1045 instead.

**Comment by jrochkind** [comment]
Aha, nice job with the repo. 

I now vaguely remember seeing this bug before and choosing to ignore it. 

We should perhaps choose to fix it, so we don't run into it again and spend time figuring it out again, ha. To be discussed.

**Comment by jrochkind** [comment]
I think the "best" UX would probably be just swapping em if they are in the 'wrong' order.

**Comment by eddierubeiz** [comment]
I see the elegance in that: a couple lines of code and no dialog boxes. Maybe a flash message indicating that we swapped the dates, or then again maybe not.

**Comment by jrochkind** [comment]
Yeah, I don't think they need a message -- what could they have possibly expected except what we did? In that scenario.

**Comment by eddierubeiz** [comment]
OK -- I swapped the two years in the controller. It fixes the bug. Happy to adjust anything, @jrochkind   - otherwise feel free to merge.
