### ISSUE TITLE
[Science History Institute Digital Collections/prod] ActionView::Template::Error: key not found: "term"

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/chf-sufia#1161]
## Backtrace

    line 7 of [PROJECT_ROOT]/app/helpers/application_helper.rb: license_label

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53196/faults/39714318)

**Comment by eddierubeiz** [comment]
This boils down to a URL capitalization error when searching for items with a given subject and rights statement URL. The URL looks like someone (or some bot) was using a combination of faceting and URL manipulation to look for materials on insecticides with a "rights statement" set to "No Known Copyright." (http://rightsstatements.org/vocab/NKC/1.0/)

With the correct capitalization, you can run this search and get 20 legitimate results:
    http://localhost:3000/catalog?f[subject_sim][]=Insecticides&f[rights_sim][]=http://rightsstatements.org/vocab/NKC/1.0/

If you don't capitalize "http://rightsstatements.org/vocab/NKC/1.0/" correctly, you'll get the error:
    http://localhost:3000/catalog?f[subject_sim][]=Insecticides&f[rights_sim][]=http://rightsstatements.org/vocab/nkc/1.0/

We're just going to catch the error and return zero results, although I can certainly imagine the underlying code being a bit less finicky.
