### ISSUE TITLE
Share to Tumblr feature doesn't import image

### ISSUE THREAD

**Issue by HKativa** [sciencehistory/chf-sufia#1172]
Observed some wonky behavior with share to Tumblr feature starting October 30th:

From Chrome, I tried to share this work (single image) to Tumblr: https://digital.sciencehistory.org/works/bc386j260. When the screen opens up in Tumblr, it imports the metadata, but the image isn't showing up. Instead of the image, I get the generic menu for adding a photo via upload or the web.

Following the same steps in IE, the image appears when the screen opens up in Tumblr, but is replaced by the generic menu after logging into Tumblr to complete the post. 

Alternately tried to use the feature both when logged into Digital Collections site and when logged out; also when logged into Tumblr and when logged out with same result. Also tried deleting cookies in Chrome with same result. Also tested share feature with multi-image record with same result.

**Comment by eddierubeiz** [comment]
Some preliminary results:

The URL we currently feed Tumblr is actually a redirect from our site that then takes the user to s3, where the image actually lives.
https://digital.sciencehistory.org/download_redirect/fq977v01f/dl_medium
At the moment, when Tumblr goes to the download_redirect link, it doesn't follow the redirect, and instead just gives up.

If you feed it an actual link to s3:
https://chf-derivatives-production.s3.amazonaws.com/fq977v01f_checksum78b1d961675f531cbd3f4040d3d31fe1b476b0ff/thumb_hero.jpg , things seem to work better.

More testing needed, but I think this can probably work.

**Comment by HKativa** [comment]
After some discussion with Eddie and Victoria, we've decided to scrap the share to Tumblr feature. Concerns include sustainability (will we just find ourselves back in the same pickle if/when Tumblr changes something 3 months from now?) and return on investment (according to Google Analytics, the share to Tumblr feature has been used by external users 6 times since February 2018). We also have concerns about Tumblr's longevity and our use of it in light of changes to its content policy.  Staff is comfortable reverting to our old workflow of downloading images and linking back to the Digital Collections site.
