### ISSUE TITLE
Some PDF thumbnail generations failing silently 

### ISSUE THREAD

**Issue by sanfordd** [sciencehistory/chf-sufia#1176]
Some PDFs, including https://digital.sciencehistory.org/works/2z10wr24q, failed to generate a thumbnail when uploaded. We did not receive a honeybadger error for this failure.

When @eddierubeiz did a manual regeneration the thumbnail appeared correctly.

The log on the jobs server does show it attempting to make the derivatives for this work.
`I, [2018-11-01T11:00:55.742446 #2355]  INFO -- : [ActiveJob] [CreateDerivativesJob] [47bef4f1-e016-487b-a31a-7bfda4adcb83] Performing CreateDerivativesJob from Resque(jobs_server) with arguments: #<GlobalID:0x0000000008311d40 @uri=#<URI::GID gid://chufia/FileSet/kd17ct876>>, "kd17ct876/files/8a13b34b-924d-4b07-9ed6-cec99b23c295", "/tmp/working/kd/17/ct/87/kd17ct876/Battista_OA_0103_FULL.pdf"`

**Comment by jrochkind** [comment]
@sanfordd reported that the "OOM killer" killed the worker jobs. 

https://linux-mm.org/OOM_Killer

What does it mean that we're "running out of memory"? Does that machine have no swap?  At what point does the OOM Killer activate? The man page suggests that when it's doing what it's doing, it's really required to keep the machine functioning at all, the machine is gonna be totally non-functional if it doesn't. Is that true?

* We can investigate less memory intensive ways to make a thumb out of a PDF. (Can you make an issue with links to the particular files that caused the problem, so we can test them? Also, if you know, ways to see how much memory a thing is using).
* We can investigate tuning the OOM killer.
* We can investigate adding more RAM (or just swap?) to the machine.
* Or we can create a separate queue with separate workers (even on a separate machine, if we want), just for thumbnail generation, or possibly even just for PDF thumbnail generation.

**Comment by eddierubeiz** [comment]
I manually regenerated the following derivatives using [the procedure outlined in the wiki](https://chemheritage.atlassian.net/wiki/spaces/HDCSD/pages/15368194/Application+administration)


- https://digital.sciencehistory.org/works/2z10wr24q
- https://digital.sciencehistory.org/works/5t34sk51n
- https://digital.sciencehistory.org/works/9019s341g
- https://digital.sciencehistory.org/works/x633f188n
- https://digital.sciencehistory.org/works/vt150k099
- https://digital.sciencehistory.org/works/pg15bf791
- https://digital.sciencehistory.org/works/bn999774m
- https://digital.sciencehistory.org/works/nz806057k
- https://digital.sciencehistory.org/works/7m01bm67f

Jonathan suggested we look at the [failed jobs list](https://digital.sciencehistory.org/admin/queues/failed) too .

**Comment by sanfordd** [comment]
The OoM killer activates when the machine is in danger of running out of all RAM. Right now we don't keep any significant sized swap drives on the jobs machines, but adding them would be a trivial task.

**Comment by jrochkind** [comment]
Here's what I think:

1) We should add swap. Jobs servers, since they are async to begin with, are the ones that can _most_ handle being slow cause of swapping we'd rather thave them be slow than crash.  (we might want, at least initially, to get a monitoring alarm when [significant] swapping happens, if possible?)

2) We should rewrite thumb generationt o use vips. I wrote it in term sof IM because I mistakenly thought vips couldn't load PDFs. I believe in fact vips can load PDFs, it just can't write them. For other work, vips has used significantly less RAM than IM, so it likely will here too.  vips _may_ need to be compiled against "libpoppler" for PDF loading. Here is our current PDF thumb extraction code using IM CLI. https://github.com/sciencehistory/chf-sufia/blob/815bf25b6287411fb109999df61069381df15eb0/app/services/chf/create_derivatives_on_s3_service.rb#L318

**Comment by jrochkind** [comment]
@eddierubeiz Please check PDFs specifically too, they may be encountering  a different  error.

**Comment by yonyitz** [comment]
Hi @eddierubeiz  just realized this record is still missing a thumbnail:

https://digital.sciencehistory.org/works/m326m273w

Thanks for your work on this!

**Comment by eddierubeiz** [comment]
No problem - regenerated derivatives for it.

**Comment by yonyitz** [comment]
Hi Eddie, found a few more that didn't generate (I uploaded 20 records today and discovered this error; per Daniel's recommendation, I'll only upload 10 at a time in the future to hopefully prevent this issue from happening again!)

https://digital.sciencehistory.org/works/x920fx72t

https://digital.sciencehistory.org/works/ff365621b

https://digital.sciencehistory.org/works/jd472x41x

Thank you!

**Comment by eddierubeiz** [comment]
@yonyitz  -- these three thumbnails are fixed in Prod. I also have a version of the new, presumably more lightweight thumbnail recipe in Staging; let's talk soon about testing it.

**Comment by yonyitz** [comment]
Thanks, Eddie!  Looking forward to testing it!

**Comment by eddierubeiz** [comment]
This is fixed in production, but I'm leaving this open until we're able to merge the corresponding Ansible pull request (https://bitbucket.org/ChemicalHeritageFoundation/ansible-inventory/pull-requests/43/ ).

**Comment by eddierubeiz** [comment]
Closing -- the ansible PR is merged. Thanks for helping out with this, everyone.
