### ISSUE TITLE
Ingest failed to upload three tiffs

### ISSUE THREAD

**Issue by yonyitz** [sciencehistory/chf-sufia#1179]
When attempting to ingest 27 tiffs from the cloud server to Samvera on 10/30 (before 3:52 pm), only 24 tiffs ended up being ingested.  I could have inadvertently overlooked the first three images but swore I selected them when selecting images for ingest.  At a later point, I added the remaining three images that didn't upload.  The collection can be found here: https://digital.sciencehistory.org/collections/4x51hj94t  

To test the issue, I will go into staging to replicate this process and will keep you posted if I encounter difficulties.

**Comment by yonyitz** [comment]
Just tested in staging and everything worked just fine.  Maybe a fluke unless error logs indicate otherwise.  Another thought is that maybe all the files hadn't yet finished uploading into the cloud provider and this could be why they were skipped.  Will add to this if the issue arises again!

**Comment by jrochkind** [comment]
I think you shouldn't even see them in the file picker unless they are finished uploading to the cloud provider. But you could have just clicked on the directory not noticing it had a couple less files than expected, hmm.

**Comment by yonyitz** [comment]
Thanks, Jonathan.  I suspect the latter may be the case.  I'll keep you posted if/when this arises again!

**Comment by jrochkind** [comment]
I wonder if we need to make the UI somehow different to make that mistake less likely. Well, we'll keep it in mind!
