### ISSUE TITLE
Inscription field will not disappear

### ISSUE THREAD

**Issue by yonyitz** [sciencehistory/chf-sufia#1180]
In spite of deleting the inscription field, () “”  characters still exist:

https://digital.sciencehistory.org/works/73666528n

Attempted to save edits last week and today to no avail.  Thanks for looking into this!

**Comment by eddierubeiz** [comment]
Good find!

**Comment by eddierubeiz** [comment]
I had to delete it twice but it did go away. This is a small enough bug that it's probably not worth fixing formally.

**Comment by yonyitz** [comment]
Thanks, Eddie!  After watching you, I realized I should delete the first occurrence rather than the second. Thanks for figuring this out!

**Comment by jrochkind** [comment]
There is some wackiness in current sufia code around avoiding saving empty strings to storage, even though there may be empty form fields on the form submitted. That I'm not surprised may have unexpected behavior and not be totally reliable. 

I _think_ the implementation in the new replacement app will not be subject to these same idiosyncrasies.

**Comment by yonyitz** [comment]
Good to know.  Thanks, Jonathan!

**Comment by eddierubeiz** [comment]
Oh and this old crusty bug, which I thought I had fixed. Who knows. 
https://github.com/sciencehistory/chf-sufia/issues/428
