### ISSUE TITLE
Add related URL label for Oral History Collection

### ISSUE THREAD

**Issue by yonyitz** [sciencehistory/chf-sufia#1183]
Within Oral History Collection (https://digital.sciencehistory.org/collections/gt54kn818) please update "Related URL" to read "View Oral History catalog" instead.

**Comment by eddierubeiz** [comment]
@yonyitz  -- let's discuss this on Monday. I think this is a great idea, but it might be worth broadening the scope of this to include more than collections. Also, I'm pretty sure there are other related feature requests which we might want to consider before starting work.

**Comment by yonyitz** [comment]
Sounds like a plan!  Thanks!

**Comment by jrochkind** [comment]
@yonyitz Thanks for filing the issue, filing an issue is always good and fine!

@eddierubeiz I'm trying to keep us to a _general_ procedure of not dropping whatever we're working on to look at every issue that gets filed -- and not needing to talk on Monday about every issue that gets filed either -- but instead relying on @HKativa to prioritize issues and decide when/if we should talk about/plan/implement them. 

I think that's what keeps us sane as a development team -- not always interupting our work for everything new that comes in -- as well as ensures we are spending our time on what brings business value to the organization. 

I see this one has been marked with a "please triage" label, which is great, probably useful to @HKativa and @yonyitz in keeping track of issues that haven't _yet_ been brought to the table. Which is great.

**Comment by eddierubeiz** [comment]
Duly noted!

**Comment by HKativa** [comment]
Just following up on the thread above: per a conversation with @jrochkind re Github prioritization and workflow, I've asked @yonyitz to file any issues in "backlog" and label them "please triage." I'll regularly review both the "prioritized work" and "backlog" milestones and prioritize/move issues accordingly. As confirmed with @jrochkind, the development team will continue to actively work off of issues in the "prioritized work" milestone, which should match up with what we discuss in our weekly meeting.

**Comment by jrochkind** [comment]
We will plan to do this based on re-using the HTML-enabled description fields we have for items. 

This code "sanitizes" HTML to only allow certain tags, on both form editing, and on display (to be double extra safe). The code used for items can be re-used for Collections.

**Comment by HKativa** [comment]
As discussed at the Tech check-in on 11/12/18, this issue specifically applies to the Collections form and desire to provide added context when linking to the homepage of the oral history microsite. See #1184 for related issue involving adding more context/description when linking to individual oral histories on Works form.

**Comment by yonyitz** [comment]
I'm reopening this after a conversation with Hillary and Eddie about enabling target="_blank" for collection descriptions so users aren't taken away from our site right away.  Thanks for working on this, @eddierubeiz !

**Comment by eddierubeiz** [comment]
Yup! No problem at all; not a big change.
