### ISSUE TITLE
"sort alphabetically" and drag and drop functionality not working in file manager

### ISSUE THREAD

**Issue by yonyitz** [sciencehistory/chf-sufia#1206]
When clicking on "File Manager" then "sort alphabetically" and "save," when you return to the record, the changes are not saved.  This functionality also does not work when dragging and dropping the image into the correct order and clicking save.

It seems something similar appeared in point #2 of this ticket that was closed:
https://github.com/sciencehistory/chf-sufia/issues/896

**Comment by jrochkind** [comment]
Please give the specific IDs of the works you were working on. This does work for _some_ works at some times (I just verified it worked for me in a random one on staging), so it may be particular characteristics of the particular works involved that trigger the bug.

**Comment by yonyitz** [comment]
Thanks, @jrochkind !  I was working on this record https://digital.sciencehistory.org/works/5d86p139h and was attempting to move filename 2007.509_037 (last image) in numerical order.

**Comment by yonyitz** [comment]
I'm currently working with that record now.  Let me know if I should refrain from creating child records and adding images to the child records!

**Comment by yonyitz** [comment]
Here is another record where the sort function is not working:

https://digital.sciencehistory.org/works/cc08hg69n

**Comment by yonyitz** [comment]
This is another record that needs sorting:

https://digital.sciencehistory.org/works/vt150k323

**Comment by eddierubeiz** [comment]
So here's my current understanding:

- To sort the items by title, you need to:
    - click "Sort alphabetically",
    - click "Save",
    - wait quite a while without leaving the page. (say 10 minutes for a hundred-page book)
- There doesn't appear to be anything wrong with the sorting code. However, some fileset titles contain zero-width no-break spaces, which are invisible characters that disrupt the sort order. How they got there is unclear.

For now, I've sorted '_Polygraphice_' and '_Physical apparatus_' correctly by filename, and removed the hidden characters. As for the Woodward seminar, I'm happy to help sort it; just let me know which pages are out of order.

**Comment by eddierubeiz** [comment]
@yonyitz, if it's OK with you, I'd like to close this ticket, unless we can verify there's another problem not described above.
By the way, if we want to remove these weird zero-width no-break spaces from fileset titles, we can totally do that, but that should probably be another ticket.

**Comment by yonyitz** [comment]
@eddierubeiz working on the lecture note issue and will be in touch with my findings in case it requires your help.  Will be in touch!

**Comment by yonyitz** [comment]
Okay; I've figured out that https://digital.sciencehistory.org/works/q237hs87b should follow https://digital.sciencehistory.org/works/v692t719s.  The filenames indicate the correct order placement.  The titles do not reflect order.  The drag/drop sort feature still does not work.  Hope that all makes sense!

**Comment by eddierubeiz** [comment]
So there were two things wrong with the Woodward seminar ( the tech notes below are mostly for me and @jrochkind  for future reference. )

- The item you wanted to move was not a child of the Woodward seminar item for whatever readson.
- Furthermore, the ordered_members array had a bunch of `nil` items.
This resulted in a 500 error getting thrown when you went to https://digital.sciencehistory.org/concern/generic_works/5d86p139h/file_manager , reordered the files by dragging and dropping, and hit "Save".

To fix this:

1) I added the wayward child back:
```
parent = GenericWork.find('5d86p139h')
child = GenericWork.find('q237hs87b')
parent.members <<  child
parent.ordered_members <<  child
parent.save!
```

2) I removed the `nil` items from `parent.ordered_members`:

```parent.ordered_members == parent.ordered_members.to_a.compact```

Now we can drag and drop the items around and the results are saved correctly.

**Comment by eddierubeiz** [comment]
To summarize all the notes above, the following problems can cause trouble with sorting child items in Sufia:
 - Really slow save times;
 - zero-width no-break spaces in the filenames;
- members and ordered_members arrays not containing the right items, and in particular `nil` items.
