### ISSUE TITLE
Homepage category: Periodic Tables

### ISSUE THREAD

**Issue by HKativa** [sciencehistory/chf-sufia#1218]
Aggregate using metadata from:

Subjects:
Chemical elements
Mendeleyev, Dmitry Ivanovich, 1834-1907
Periodic law
Periodic table of the elements

As discussed at Tech meeting on 1/28/2019, this topic replaces "Portraits and People" as a homepage category. Cropped file is periodic_tables_full.tif saved in P:\Othmer Library\Digital Collections - External Access\Crops for Hydra Redesign\cropped_tiffs\categories.

Collection description forthcoming - let me know if I should just post it here and send via email.

**Comment by eddierubeiz** [comment]
@HKativa - you can just post the description as a reply to this. Should have this ready for Monday morning.
