### ISSUE TITLE
Investigate GenericWork 3r074v259

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/chf-sufia#1229]
The export-import process has flagged one particular GenericWork as odd; could be a discrepancy between Solr and Fedora, or something else. If we reindex production and this problem goes away... fantastic.

Meanwhile:

GenericWork.find_each doesn't list it, and https://digital.sciencehistory.org/works/3r074v259 -- returns a 404.

In the production console:

```

beckman = Collection.find('wh246s128')
apparatus = GenericWork.find('3r074v259')

apparatus.title
=> ["2012-002_3680.tif"]

beckman.ordered_member_ids.include? apparatus.id
=> false

beckman.ordered_members.to_a.include? apparatus
=> false

beckman.member_ids.include? apparatus.id
=> true

beckman.members.to_a.include? apparatus
=> true
```

**Comment by eddierubeiz** [comment]
OK this is in Fedora, but not in Solr:

```curl --silent http://username:password@fedora_ip:8080/fedora/rest/prod/3r/07/4v/25/3r074v259 | grep title```

(returns all the RDF triples)

```    curl  --silent http://solr_ip:8983/solr/collection1/get?id=3r074v259```

retuns `{ "doc":null}`

**Comment by eddierubeiz** [comment]
This is also true in production, by the way.

**Comment by eddierubeiz** [comment]
I reindexed Staging; this does not fix the problem.

I then tried the following in the Staging console:

```
batch_adder = CHF::SolrBatchAdder.new(batch_size:1)
batch_adder.add(GenericWork.find('3r074v259').to_solr)
batch_adder.finish
batch_adder.commit
```

which *did* index the item.

**Comment by eddierubeiz** [comment]
OK -- I went ahead and fixed this in production.

**Comment by jrochkind** [comment]
It's weird that reindexing didn't fix it, but then a _differnet_ kind of reindexing fixed it. Something wrong with our reindexing I guess. The whole system is pretty crazy. I'm not inclined to debug _exactly_ what was going on in the system we're trying to get out of. 

It is a credit to the import process that it found the weirdness though! That's great!

**Comment by eddierubeiz** [comment]
Yeah, the thing with it not getting fixed by the standard index procedure is just weird. But yeah, on the other hand, I think this is the last item standing in our way of a completely error-free import.
