### ISSUE TITLE
New field for projects

### ISSUE THREAD

**Issue by yonyitz** [sciencehistory/chf-sufia#1240]
Under collection on front end, please create a field entitled "Project" with drop-down selections as follows:

Atmospheric Science
Chemical History of Electronics
Imagining Philadelphia's Energy Futures
Mass Spectrometry
Nanotechnology
Oral History of the Toxic Substances Control Act
Pew Biomedical Scholars
REACH Ambler
Scientific and Technical Information Systems
Science and Disability

Please set up so multiple projects can be selected for a single record.

Thanks!

**Comment by eddierubeiz** [comment]
@yonyitz  -- This is coming along nicely (https://github.com/sciencehistory/chf-sufia/pull/1241) . It's currently in staging for your review.
When you have a minute, I will need some data-dictionary like meta-metadata -- instructions to put in the generic work form describing the new field to people filling out the form. You can just post them on this ticket.
TIA :)

**Comment by yonyitz** [comment]
Thanks so much, @eddierubeiz!  Here is the instructional text for the form: 

Select any current or past projects that the work is a part of, if applicable. If a desired entry is not available, contact the Digital Projects and Metadata Librarian.

**Comment by yonyitz** [comment]
I confirmed with Hillary that placing the project field underneath "exhibition" is the proper placement.  Thank you!
