### ISSUE TITLE
Accomodate provenance notes

### ISSUE THREAD

**Issue by yonyitz** [sciencehistory/chf-sufia#1244]
Please create new Provenance notes field which should be located underneath Provenance.  Provenance notes field should be expandable/collapsible with the default set as hidden. Please use same indexing settings as Provenance field.

Instructional form text should read as follows:
For fine art materials, input provenance notes information following Provenance Style Guide document (P:\Eddleman Institute\Museum\Collections\Art Collections\Provenance\Provenance_Style_Guide.docx). Provenance notes information can either be found in Past Perfect or within provenance files in the Museum department.

## New plan of attack

1. There will be one "provenance" field. 
    * Entering text into it according to existing museum style guide, it is multi-paragraph text with a paragraph "NOTES" separating the "main" provenance body from the "notes"
    * This field does need to be sanitized on input the same as our "description" field
2. In our view, I'm imagining a line like `<%= provenance_summary, provenance_notes = split_provenance(actual_provenance_data) %>`
    * `split_provenance` (not necessarily the right name I dunno) will be a rails helper method, whose implementation can be something like `actual_provenance_data.split("\n\nNOTES\n\n")`
3. We will have custom view logic for displaying, where the `provenance_summary` is just on the page (formatted for display like "description"), while the `provenance_notes` will be hidden behind an expand/collapse disclosure of some kind. 
    * Doesn't necessarily need a separate "label" on page, it can probably be in the "provenance" section, just below it. 
    * While making it full-width makes ("under" label rather than along side) might sense for such length data, to avoid messing up the page design, it would probably need to be at the _top_ (right under description) or _bottom_ (under "Credit line") if it were going to be full-width. Without further redesign of this page, I don't like a full-width field breaking up the "table" label/value layout in the middle of it. 
    * Both the "summary" and "notes" need to be sanitized/formatted same as "description" field

Note: Step 1 needs to be done in scihist_digicoll if not already. Subsequent steps not necessarily yet, since we don't really _have_ a front-end display yet (but hopefully will soon).

**Comment by jrochkind** [comment]
Is this meant to be available to the public, or staff-only?

Can you give us an example of what would go there?  

I'm not sure if we have any features for "expandable/collapsible with the default set as hidden" -- do you mean on the "edit" form, or on the page showing an item?  Are there any current examples in our app of a field that is "expandable/collapsible with the default set as hidden"?

**Comment by yonyitz** [comment]
Thanks for your questions, @jrochkind.  Eddie and I have been discussing this and he asked me to create a Github ticket.  Here is an [example record](https://staging.digital.sciencehistory.org/works/c534fp505) Eddie created showing how extensive notes fields can potentially be.  We thought that a solution could be having an expandable/collapsible notes field that would reduce scrolling on the page showing an item (not on the edit form). The provenance notes field should be public.

**Comment by eddierubeiz** [comment]
Hey @jrochkind - this is in response to how voluminous provenance metadata shows up on the item display page. If you take one of the examples cited by the museum staff on the P drive like https://www.mfa.org/collections/object/double-portrait-of-trudl-33706 you'll see 3/4 of the text is notes. The narrow column we use for metadata (see e.g. https://staging.digital.sciencehistory.org/works/c534fp505 ) doesn't really go well with large chunks of text. Hence the idea of a show/hide toggle.

**Comment by eddierubeiz** [comment]
We should also consider having the provenance metadata and/or notes going *under* their labels rather than alongside them, as we do with citation metadata. This definitely makes better use of horizontal space.

**Comment by jrochkind** [comment]
An example record in staging with actual copy-and-pasted from PastPerfect data:

https://staging.digital.sciencehistory.org/works/12579s91d

(Beware, staging may refresh and lose it at some point. So actually I'll put it here too, copied out of the 'edit' text box from that record:)

```
Marie Therese Trinidad Brocheton, Comtesse de La Beraudiere (1872-1958) [1]; (sale, Collection of the Countess de la Beraudière, American Art Association, Anderson Galleries, Jay Gould Mansion, New York, 1930, lot 20 (with "Le Notaire", not illustrated).
William Fox, acquired 1930; by descent to his widow, Mrs. William Fox.
(Sale, Kende Galleries, New York, 1-2 December 1942, lot 58 [with "Le Notairem," $320.00].)
Fisher Scientific, Pittsburgh, PA; Fisher Scientific International Inc., Hampton, NH (acquired by Chester G. Fisher), circa 1942-2000.
The Chemical Heritage Foundation, 2000 (from Fisher Scientific).

Notes:
[1] Marie Therese Trinidad Brocheton, Comtesse de La Beraudiere (1872-1958) was a French salonniere and literary figure. Madame de La Beraudiere was a friend of the famous novelist, Marcel Proust, and she was the mistress of the wealthy Henri Charles, Comte de Greffuhle (1845-1932). Madame de La Beraudiere was the model for Proust's character Odette, the mistress of the Duc de Guermantes in his series of novels A La Recherche du temps perdu (In Search of Lost Time).
```

**Comment by sanfordd** [comment]
I'll keep an eye to avoid staging refreshes until this ticket is closed.

**Comment by eddierubeiz** [comment]
Adding some horizontal space after the "Notes..." link and changing its text to "Show Notes".

**Comment by yonyitz** [comment]
Erin has approved line breaks between provenance info/notes.  Thanks for working on this to make it happen!

**Comment by yonyitz** [comment]
Here are the sample records with data copied from Past Perfect:

https://staging.digital.sciencehistory.org/works/x920fx36z

https://staging.digital.sciencehistory.org/works/12579s91d

Let me know if you need more sample data.  Thanks!

**Comment by eddierubeiz** [comment]
I'm closing this ticket for now; if any more work is needed after a few provenance lists are added to production items, we can always open a new ticket for that.
