### ISSUE TITLE
Edit access for promoting child works

### ISSUE THREAD

**Issue by yonyitz** [sciencehistory/chf-sufia#1251]
I granted Ashley edit access to this record but she cannot promote anything to child works.  Does this mean I have to grant edit access to each individual file or did something go awry? https://digital.sciencehistory.org/works/9593tw10r

**Comment by eddierubeiz** [comment]
Hey - sorry for the delay on this. Something definitely did go awry, but I was able to manually grant access to all the files in the book to Ashley. 

Note:
The current front-end interface for granting access to all children of a particular item to a particular user is simultaneously confusing, slow, and buggy. Practically speaking, for a book with more than a handful of pages, it's almost unusable unless you have access to a console, to ensure that your actions have actually worked.

**Comment by eddierubeiz** [comment]
Recipe I used:
```
parent = GenericWork.find('9593tw10r')
the_users= ["aaugustyniak@sciencehistory.org", "njoniec@sciencehistory.org"]
parent.members.map {|x| puts x.edit_users; x.edit_users=the_users; x.save!; puts "Done with #{x.id}"}
puts "Doing parent:"
parent.edit_users=the_users;
parent.save!
puts "Done!"
```

**Comment by jrochkind** [comment]
Permissions are _weird_ in the sufia app, it's possible this is a known limitation of sufia, I vaguely recall it.

**Comment by eddierubeiz** [comment]
I'm closing this; we solved the problem.
