### ISSUE TITLE
Block common bots not associated with search engines

### ISSUE THREAD

**Issue by sanfordd** [sciencehistory/chf-sufia#1271]
We should start blocking bots whose scraping of the site doesn't actually add our content to search engines or other tools that help people find us.
Current bots to block
- MauiBot
- centurybot9@gmail.com
- AhrefsBot
- SemrushBot
- BLEXBot

The first two are somewhat mysterious as to their purpose and owners, the last 3 are well described and clearly note they follow robot.txt and the limits they work under which are not unreasonable. Since we don't use or want ads or external marketing on our site though, blocking them should save us some traffic and reduce some of the issues we've had hopefully.

**Comment by jrochkind** [comment]
Those strings are the exact strings that shoudl appear in robots.txt?

**Comment by sanfordd** [comment]
Those are the user agent strings we should use. I fixed a capitalization typo on AhrefsBot.
