### ISSUE TITLE
Place Digitization Funder field after Credit Line/Additional Credit on front end

### ISSUE THREAD

**Issue by yonyitz** [sciencehistory/chf-sufia#1278]
Due to metadata guidelines, in consultation with Hillary, we've decided to move the Digitization Funder field underneath "additional credit" field (or "credit line" when "additional credit" is blank).

**Comment by eddierubeiz** [comment]
We'll deploy this next week but it's ready to go.

**Comment by eddierubeiz** [comment]
This is now in production.
