### ISSUE TITLE
Robert J. Bauman collection thumbnail 

### ISSUE THREAD

**Issue by yonyitz** [sciencehistory/chf-sufia#1282]
File is 3484zh868_full.tiff saved in P:\Othmer Library\Digital Collections - External Access\Crops for Hydra Redesign\cropped_tiffs\collections. I expanded canvas to include black below note so hopefully entire note can be included.  If not, let me know and I can readjust!

**Comment by eddierubeiz** [comment]
Got it. The collection thumbnail will be named 
`app/assets/images/collections/4x51hj94t_2x.jpg`.
