### ISSUE TITLE
thumbnail in edit works form (feature request)

### ISSUE THREAD

**Issue by archivistsarah** [sciencehistory/chf-sufia#298]
Functionality we had in sufia 6, lost in 7. Curators would like a thumbnail to display on the edit works form so they can see what they're describing without opening another window/tab/file. Ideally would have the lightbox, too.

**Comment by jrochkind** [comment]
"have the lightbox" probably now means "option to open a viewer"?  That is somewhat tricky although definitely possible, so re-commitment/clarification would be good. :)

**Comment by HKativa** [comment]
We've added this functionality to Kithe so closing ticket as far as Sufia is concerned.
