### ISSUE TITLE
New error pages

### ISSUE THREAD

**Issue by hackmastera** [sciencehistory/chf-sufia#333]
- [ ] 404 (not found) in public/404.html
- [ ] 422 (unprocessable entity) in public/422.html (note: I've never seen this one but presumably there's some way to get it?)
- [ ] 500  (internal server error) in public/500.html; this is the one our users generally see when an error has occurred
- [ ] apache
- [ ] passenger

Screenshot of the 404:
![screen shot 2017-04-18 at 4 05 27 pm](https://cloud.githubusercontent.com/assets/845363/25150863/6a0d5d04-2451-11e7-8a22-1d9178af6eda.png)

Screenshot of 500:
![screen shot 2017-05-30 at 9 57 34 am](https://cloud.githubusercontent.com/assets/845363/26586854/7bceee48-451e-11e7-8d17-6828b221c686.png)

Screenshot / gist of passenger error:
![screen shot 2017-07-13 at 9 49 30 am](https://user-images.githubusercontent.com/845363/28169548-b2eaf43a-67b0-11e7-993a-110a841cabfa.png)
https://gist.github.com/hackmastera/c5cb8903028028c3fee3746ab0361c7b

**Comment by hackmastera** [comment]
/usr/local/lib/ruby/gems/2.3.0/gems/passenger-5.0.10/resources/templates/

**Comment by hackmastera** [comment]
Here's a 404 page not coming from the rails app; not sure its origin.
![screen shot 2017-05-02 at 10 10 05 am](https://cloud.githubusercontent.com/assets/845363/25621534/a21e4ca2-2f1f-11e7-962a-6e61693adbdc.png)

**Comment by hackmastera** [comment]
oh nevermind that's the chf top-level 404; I left out a subdomain. deleting.

**Comment by MDiMeo** [comment]
@hackmastera Can we get a screenshot of the existing 500 error? If I remember correctly, what was confusing about this one was that it said the administrator had been contacted already but we actually weren't.

**Comment by hackmastera** [comment]
@MDiMeo I just added it to the issue description. That's the error you usually see when there's a bug. The one that says the administrator has been contacted is something else; we haven't nailed that one down yet. I think one of the apache-level errors.

**Comment by hackmastera** [comment]
We aren't able to force any apache error. There is some info on apache error document configuration, in `conf-available/localized-error-pages.conf`. That file also mentioned the default location of apache's error documents, which is `/usr/share/apache2/error/` It's unclear to me whether those default files are in use, though; there is conflicting documentation suggestion that they are the default but also suggesting we need to enable / uncomment some configuration for them to take effect. I believe the text of the 403 code I saw earlier (no longer getting that because I got passenger half set-up) matches that of the `HTTP_FORBIDDEN` file. 

Regardless, none of these contain any form of the work 'notify' so don't appear to be the root of the elusive "the administrator has been notified" message.

However, we do still need to set the admin email address, which is used in some of these error messages. I'm creating an action item on the systems tracker.

Next step is to look at updating the passenger error screen to include our email address.

**Comment by hackmastera** [comment]
Passenger error screen can be turned off so that the apache one shows instead; that's pretty much the only option. Ideally you'd do this in combination with making a nicer one for apache, which is not currently our highest priority. However, the apache one does include the information we want, once we've configured apache with our email address (see screenshot)

Configuration to turn off passenger error has been added to the systems tracker.

Moving this out of the soft launch milestone since we've now met the most immediate requirements.

![screen shot 2017-07-14 at 4 12 19 pm](https://user-images.githubusercontent.com/845363/28229061-3eb1247c-68af-11e7-9e04-72a6150d2c5a.png)

**Comment by jrochkind** [comment]
Also includes, why do we seem to be getting apache error pages when deployed, instead of the ones from the rails app?

**Comment by hackmastera** [comment]
Are you sure? If you see this again can you screenshot? I didn't know this was happening. The rails ones look like the 404 and 500 above.

**Comment by jrochkind** [comment]
Yes. Just go to a 404. https://digital.chemheritage.org/adfad/adfadf

I don't think this _used_ to happen either, I have no idea what changed, I spent a few minutes trying to look into it last week but couldn't get anywhere.

**Comment by hackmastera** [comment]
:(

**Comment by jrochkind** [comment]
@MDiMeo who is going to design these or otherwise decide what they should be? What are the goals of this ticket? Thanks!

**Comment by jrochkind** [comment]
@MDiMeo note that to the extent this is about branding, we still don't know what kinds/degree of change will be required for rebranding, and wont' until Dec 1.  Because these are error pages, they will essentially be 'static' pages, and won't share logic with our ordinary pages, any rebranding changes will have to be done here separately.

**Comment by MDiMeo** [comment]
@jrochkind That's a really good point, and thanks for the reminder that they'll be static pages. It's probably more appropriate to move this to a later milestone.

In the meantime, let me write notes here so I don't forget what we discussed. At today's check-in we agreed:
- @mdimeo will mock-up a design for 404 and 500 pages in Photoshop. 404 will have a "page not found" message and this painting of an[ alchemist's experiment gone wrong](https://digital.chemheritage.org/concern/generic_works/w3763731m). The 500 will have this [explosion of hydrogen and oxygen](https://digital.chemheritage.org/concern/generic_works/h989r376z) and a "something went wrong" type message. 
- When we're ready to deploy these newly designed pages, @sanfordd will undo the earlier decision to deliver errors from Apache and will go back to using Rails.

**Comment by jrochkind** [comment]
@MDiMeo honeybadger optionally has a feature where the user, when getting an error, can optionally enter something about what they were doing at the time or anything else they want us to know, that will get attached to the honeybadger error. 

What do you think about using that feature?

**Comment by jrochkind** [comment]
https://github.com/phusion/passenger/issues/2007

**Comment by jrochkind** [comment]
@MDiMeo if we choose to allow users to fill out feedback on errors, here is what the default honeybadger form looks like. We can restyle it however we'd like. 

https://d2auf2z1gawrdi.cloudfront.net/images/features_2_d.png

**Comment by MDiMeo** [comment]
@jrochkind We're going to make a 404 and 500. Do you only want that error feedback box on the 500?

Also, for our page mock-ups, do you have a preferred page size or any other specs you'd like us to adhere to?

**Comment by jrochkind** [comment]
i'm not sure if the 404s are reported to honeybadger at all, not sure right now. Could just be on the 500. 

No specs I can think of. I'll of course have to style it so it works somehow at any page size, including mobile, so it would be good to keep that in mind, if it needs a somewhat different look on very small screens.

**Comment by jrochkind** [comment]
Do we have anything for this yet, @MDiMeo ?

**Comment by MDiMeo** [comment]
We were delayed by not having the new fonts and Jay trying to frontload some stuff before Cat leaves. Looks like next week, so I guess we'll miss the launch date, but soon after.

**Comment by jrochkind** [comment]
one more page we might want to consider is a "down for maintenance" page that exists already in bare-bones format for when we want/need to make the site inaccessible for maintenance.

**Comment by catlu** [comment]
@MDiMeo @jrochkind Jay exported his images for the error pages, and I put them in a folder under the Digital Collections - External Access folder.

**Comment by MDiMeo** [comment]
Here is a link to the folder: https://files.sciencehistory.org/fl/mKvuXoC9Qq
At today's photography check-in, Jay said he could update these if he knows exactly what assets we want or how to save them. 

For the 404: I like the image "404error2", but it would need a header above it. We could also follow the model from the Institute's website and include a search box that takes you back into Digital Collections. We could make the image a clickable link that takes you to [this alchemist painting](https://digital.sciencehistory.org/works/w3763731m) within the Digital Collections. 

For the 500: I like "error2" as the mock-up (though the header should include the Digital Collections on the right.) But I think "Oh no! Something went wrong!" would probably look better if centered across the top of the screen and in larger font. The "learn more about this man's failed experiment" should be a hyperlink back to [that image in the Digital Collections](https://digital.sciencehistory.org/works/h989r376z).

**Comment by jrochkind** [comment]
https://medium.com/@tair/custom-error-pages-in-rails-you-re-doing-it-wrong-ba1d20ec31c0

**Comment by jrochkind** [comment]
> For the 500: The "learn more about this man's failed experiment" should be a hyperlink back to that image in the Digital Collections.

When we're showing an error, there's no guarantee that any links to any other parts of the site will work, so don't really wanna link this. On the 404, link is no problem though.
