### ISSUE TITLE
Inscription location field doesn't update after save

### ISSUE THREAD

**Issue by catlu** [sciencehistory/chf-sufia#428]
An update to inscription location field doesn't show up in the record view (but the update shows up when you return to the edit form). I can get around it by adding a new inscription and removing the old one.

**Comment by catlu** [comment]
Lower priority because inscription locations don't get updated often and can be worked around by adding another value.

**Comment by hackmastera** [comment]
This started happening with sufia 7.3 upgrade. The object probably needs to be reloaded at indexing time or something.
