### ISSUE TITLE
Add Department metadata field to batch edit

### ISSUE THREAD

**Issue by catlu** [sciencehistory/chf-sufia#925]
Is there any way to do this easily? I have to make some 120+ edits and realized Department isn't an editable field in the batch edit workflow.

**Comment by jrochkind** [comment]
@MDiMeo Did you mean I should try to add this field to the form, or did you mean I should try to 'manually' add it to the 120+ records @catlu mentioned?  I thought you meant the latter, but @catlu is asking for the former.

**Comment by MDiMeo** [comment]
I am wondering if there would be a quick way to change the data on the back-end as a short-term solution if she gave you the information about the 120+ records. @catlu does want this fixed in the UI so she can handle it herself in the future, but she isn't in a rush about that.

**Comment by jrochkind** [comment]
In that case, @catlu Can you give me specs for what you need changed in existing records?  List of record ID's, and what you want me to set their Department to, I guess?  I should probably be able to do that.

**Comment by catlu** [comment]
@jrochkind It would be every record with a Sierra bib number of "b1071546" that has Department 'Library', to be changed to 'Archives.' There should 102 records like that at this point--I did some edits yesterday.

**Comment by jrochkind** [comment]
OK, that's harder without the list of ID's, but I think I can figure it out.

**Comment by jrochkind** [comment]
@catlu every record with Sierra bib number "b1071546" should be changed to have department "Archives", correct? For those with that bib number, no other department should be there.

**Comment by jrochkind** [comment]
There appear to be 139 total records with Sierra bib number "b1071546". List of all ID's here: https://gist.github.com/jrochkind/f81323a16de44ef8b642c53d686141ea

Confirm that I'm doing the right thing, and tell me to pull the trigger, and I will ensure all 139 of those ID's have Department set to "Archives".

**Comment by catlu** [comment]
Confirming @jrochkind! Go for it.

**Comment by jrochkind** [comment]
Done! Will leave this ticket open with the feature request.

**Comment by MDiMeo** [comment]
Perfect. Thanks so much @jrochkind

**Comment by catlu** [comment]
Sweet, thanks @jrochkind!
