### ISSUE TITLE
Citation displays on-page

### ISSUE THREAD

**Issue by MDiMeo** [sciencehistory/chf-sufia#931]
Will need more discussion, including actual examples of how to cite various items, especially archives.

**Comment by MDiMeo** [comment]
Guide for the Institute says to use [Chicago Style](http://www.chicagomanualofstyle.org/home.html).

**Comment by sanfordd** [comment]
Sample works were added to Othmer Library/Digital Collections - Internal Access as citation-analysis.

**Comment by sanfordd** [comment]
Sample citation works were added here: https://files.sciencehistory.org/dl/p0mymEW90D/citation-analysis.rtf_

**Comment by MDiMeo** [comment]
Notes from our meeting on 2/26/2018:

- @jrochkind will run a script to locate all works that have "from" followed by italics in the description field (such as the[ Solar Prominence example](https://digital.sciencehistory.org/works/bk128b76p).) @catlu will consider this and recommend a field for the title of the container (possible Source or similar.)

- Creator will be default author if there are multiple entries (creator, author, etc.) If no creator, author is ok.

- For works within containers, we will reference the smallest unit in the container and pull the information on the container from the new container/source field. We will also pull the creator of the smallest unit in the container.

- @mdimeo will talk with Elsa and Jim about the value of including shelfmark information in the Digital Collections to aid in citations. May write the script to look at "manuscript" and "library" so it knows that manuscript books in the library need this information.

- For archives, books, etc;: dates that say "before 1946" will appear as "no date". Works that have multiple dates will be aggregated into a range. If a range is included, it will be included as is.

- For Museum Objects, non-text, pull the date from the "date created" field (seen in the staff view). Add photograph to citation, but does not need to appear in metadata.

- Archival Series and Subseries are not needed in the citation or the RIS export.

- Archives should be cited in the following order: Collection, Box #, Folder #.

**Comment by jrochkind** [comment]
Searching for `/from \<i\>/i` in descriptions to try and find "orphaned excerpts", found only 20 works. May not have found them all. But maybe we leave this particular edge case issue for later, after the bulk of the citation export, so we can re-evaluate priorities and see if any other problems come up. 

```
@clu @mdimeo my search for “from <i>” only found 20 works. It’s possible it’s not getting everything (maybe not always italisized?). Maybe we just ignore that particular edge case for now, get the rest of citation export working, and re-evaluate priorities?


jrochkind [4:03 PM]
added this Plain Text snippet: Untitled 
8s45q8805
8s45q881f
kh04dp72m
nv935287v
wh246s18x
0c483j42m
8910jt61f
br86b3609
5138jd856
44558d32r
p5547r43n
8623hx748
hq37vn58w
4x51hj03c
fj236219b
4b29b614k
9z9030273
5712m6834
9306sz691
bk128b76p
```

**Comment by jrochkind** [comment]
@catlu also asked for the list of any records that contain the word "from" as well as italics, not neccesarily next to each other. This time there were 302 matches, [here](https://gist.github.com/jrochkind/7c5fb2ae568bc98ac0e584b3eb9ec2cb).
