### ISSUE TITLE
DPLA integration

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/chf-sufia#965]

**Comment by jrochkind** [comment]
From: Rachel Appel [mailto:rappel@temple.edu] 
Sent: Thursday, January 25, 2018 11:59 AM
To: DiMeo, Michelle <MDiMeo@chemheritage.org>
Cc: Lu, Cathleen <CLu@chemheritage.org>; Stefanie Ramsay <stefanie.ramsay@temple.edu>
Subject: Re: DPLA for our Digital Collections
 
Hi Michelle and Cat,
 
It's wonderful to hear from you guys!
 
This is very exciting news and I know it's been very hard work over the past few years, so congratulations! 
 
) Here is a quick checklist for contributing institutions that gives an overview of the general requirements for sharing your data.
PA Digital Checklist for Contributing Institutions

2) Attached is our Onboarding Overview so that you can see what our onboarding procedure is. Ongoing DPLA harvests will generally be scheduled quarterly.
PA Digital Onboarding Workflow​

3) Here is our current draft of our Metadata Guidelines. We update them when there are changes to the DPLA's metadata guidelines.
PA Digital Metadata Guidelines
 
Also, have you or your colleagues been added to the pa-digital@hslc.org listserv?  It is a great resource to learn about digital library issues.  You can subscribe yourself here: https://mail.palibrary.org/mailman/listinfo/pa-digital

Our next harvest deadline is March 9th and the following one will be mid-June and we would need the agreement letter signed prior to those deadlines. I know Samvera does have an OAI output, but we've found that not all OAI applications are exactly the same. There may be some troubleshooting to make sure your data output works with our aggregator software. We are currently working on integrating several Islandora repositories so I'm hoping it will be similar. Our metadata reviews usually take a couple of weeks depending on how many collections there are, but the technical compatibility work can take much longer. 
 
Please let me know if you or your colleagues would like to set up a meeting with PA Digital to more specifically answer your questions. We are planning an orientation webinar in February that will go over the above documents and I can let you know when that's scheduled.
 
Best,
Rachel

**Comment by jrochkind** [comment]
UCSB used  the standard release [blacklight_oai_provider](https://github.com/projectblacklight/blacklight_oai_provider) (6.0) in their curation_concerns (not sufia or hyrax) based app. Commits from UCSB can be found here: https://github.com/projectblacklight/blacklight_oai_provider

I know many devs were using a fork of blacklight_oai_provider instead; not sure why, or if they still are, or where to find it. Will post to samvera-tech.

**Comment by jrochkind** [comment]
@catlu Should "collection" records be in the OAI-PMH feed for DPLA? I suspect not? 

They are at present, I gotta fix that if they ought not to be.

**Comment by catlu** [comment]
@jrochkind Not the collection records, no.

**Comment by jrochkind** [comment]
More docs:

Draft of EDTF, which is now hard to find on the web, and will be replaced by a final ISO version behind a paywall. :(  http://www.loc.gov/standards/datetime/pre-submission.html

DPLA Geographic and Temporal guidelines: https://docs.google.com/document/d/1lfiJ8yoZf1fAoR5vmJoHpWQO63eKeL8HDGVupCocfoM/edit?usp=sharing

**Comment by jrochkind** [comment]
Waiting on DPLA for review, sent it to this early last week.
