### ISSUE TITLE
Add facets to collections pages

### ISSUE THREAD

**Issue by MDiMeo** [sciencehistory/chf-sufia#975]

**Comment by jrochkind** [comment]
@MDiMeo do we want the "public domain only" and date limit input boxes here, just like an ordinary search form?  I think probably, the goal here is really "make collections page search work just like ordinary search with all the same features, but limited within a collection". Yes?

**Comment by MDiMeo** [comment]
Yes, the goal is "make collections page search work just like ordinary search with all the same features, but limited within a collection". I think the facets should be the same. But I wonder if we are going to have to work with the design to make it clear to folks that they are limiting within a Collection. At the moment, as we all know, there is no Collections facet where you can turn off that box and restart.
