### ISSUE TITLE
Improve metadata for child works

### ISSUE THREAD

**Issue by MDiMeo** [sciencehistory/chf-sufia#989]
When working on the RIS export and the citation management improvements, we will have to improve some of the metadata for child works, some of which don't have parent relationships formatted in a way that the computer can understand them, like this one: https://digital.sciencehistory.org/works/bk128b76p We will collect more examples and have a discussion with @archivistsarah and @catlu.

**Comment by jrochkind** [comment]
Another issue is I believe we have some parent/child works where the parent should _not_ be used in the citation, they are being used for organizational/discovery purposes only. We should find an example of that to consider. There may not at present be a way for the software to tell the difference between parents that should be part of citation and parents that should not. 

A separate purely technical issue is that it's difficult to efficiently _get_ parent information from Sufia, for using to determine proper citation. But I'll just have to find a way around that, it'll just require some ugly code, but if it's a requirement it's a requirement!
