### ISSUE TITLE
New Metadata field: Shelfmark

### ISSUE THREAD

**Issue by catlu** [sciencehistory/chf-sufia#998]
Under Physical Container field, after Page. (I don't think a URI is needed here unless we decide to eventually break everything out.) Accepts both letters and numbers, such as _MS13_.

Updated usage text for Physical Container field:

"For archival and serialized materials: specify either box/folder or volume/part numbers, where relevant. For library manuscripts, specify shelfmark."

**Comment by jrochkind** [comment]
Because of the odd way we've done physical location fields, where they are all packed into one field in the actual underlying store (don't totally understand why we've done this), this is harder to do than adding a field ordinarily is.  But it can be done.

**Comment by jrochkind** [comment]
@catlu Is this related to citations, do we want shelfmark to be showing up in citations?  If so, can someone add that to the citations ticket, with an example of how a citation with shelfmark should look? Thanks!

**Comment by catlu** [comment]
Yup, it's related only to the 'Manuscripts' genre from the Library department. @sanfordd do you mind adding an example citation of that?

**Comment by sanfordd** [comment]
I think our only example for that in production right now is Newton, is that correct @catlu ?

**Comment by catlu** [comment]
There's one other manuscript right now @sanfordd! Work id: pn89d712c.

**Comment by sanfordd** [comment]
I want @MDiMeo to check this, but here's a quick guess on the one @catlu mentioned above
Bonus, Petrus. _Pretiosa margarita novella_. [1450-1480]. MS 3. Science History Institute, Philadelphia, https://digital.sciencehistory.org/works/pn89d712c

I needed to use the OPAC to get the shelf detail, and chose to use the whole institution rather than the library specifically. Went with italics since it is book length, but it's probably fine either way. Date range got bracketed since Chicago uses that for uncertain dates.

**Comment by jrochkind** [comment]
closed by #1006

**Comment by jrochkind** [comment]
@sanfordd your previous "Library" (non-Archives or Museum) citation examples do not have "Science History Institute, Philadelphia" in them, which I interpret as the "hosting archive". 

But this one does.  Do we want that hosting archive to be in the citation for "Library" items _only_ when they have a shelfmark, then?

**Comment by jrochkind** [comment]
@MDiMeo answers:

> i think it's only in archives and museum, and only in library if there is a shelfmark. part of the issue is that manuscripts like that are sometimes housed in archives in other institutions. we happen to do it in our library's rare book department

> so that is correct (only include hosting archive in library items if they have a shelfmark)

**Comment by catlu** [comment]
Hey @jrochkind, was going to send out an email to let folks know about the new fields, but noticed the usage text for this is still the old one. Can you update when you get a chance?

"For archival and serialized materials: specify either box/folder or volume/part numbers, where relevant. For library manuscripts, specify shelfmark."

**Comment by jrochkind** [comment]
@catlu sorry I missed that, thanks, deployed to production now.
