### ISSUE TITLE
New Metadata field: Source

### ISSUE THREAD

**Issue by catlu** [sciencehistory/chf-sufia#999]
Free text field, located after Exhibition and before Series Arrangement on metadata entry form, and then after Collection and before Series on record view page. (Since the Source field conveys both intellectual and physical information, I think it could fit in the description section too if anyone feels strongly about that. I just thought it made the most sense here with our metadata.) Non-repeatable.

URI: http://purl.org/dc/elements/1.1/source

Usage text for metadata entry form:
"For standalone digitization from a larger work, use for the name of the work from which the described material is derived. Can be left blank if the digital object is related to its parent work in the repository."

@jrochkind Not sure how much extra work it would be, but if you could add this field to the Batch edit, I could probably tackle the 300+ records faster!

**Comment by jrochkind** [comment]
I think it may make sense to include it in the top section instead of the "physical location" section, perhaps even very prominent similar to the "Part of" sub-head?

**Comment by catlu** [comment]
That's not a bad idea--it _is_ serving the same function as the "Part of" subheading, just without the parent work link.

**Comment by catlu** [comment]
In fact if we want to make the field read on the user side as "From" or "Part of" instead of Source, it might be easier to understand.

**Comment by jrochkind** [comment]
Maybe exactly like the current `Part of`, but without being a hyperlink since there's nothing to link to.

**Comment by jrochkind** [comment]
@catlu I can't figure out how to make it non-repeatable at the moment. Sufia really wants everything to be repeatable. Some of our existing things that we made non-repeatable -- I can't quite figure out how they were done _plus_ some of them are buggy (we have existing issues filed on certain fields being not editable or deletable, this is related). 

How disastrous is it if it's repeatable?

**Comment by catlu** [comment]
@jrochkind not disastrous, really. I can probably keep an eye out at the content level (I do that with most things right now anyway, so not a big deal).
